# Generated by Django 2.0.3 on 2018-05-10 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180312_2139'),
        ('dates', '0007_auto_20180510_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupKeyDateException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Новое время')),
                ('group', models.ForeignKey(help_text='Группа, для членов которой будет применено исключение', on_delete=django.db.models.deletion.CASCADE, related_name='key_date_exceptions', to='groups.AbstractGroup')),
                ('key_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_exceptions', to='dates.KeyDate')),
            ],
            options={
                'verbose_name_plural': 'key date exceptions for groups',
                'verbose_name': ' key date exception for group',
            },
        ),
        migrations.AlterModelOptions(
            name='userkeydateexception',
            options={'verbose_name': 'key date exception for user', 'verbose_name_plural': 'key date exceptions for users'},
        ),
        migrations.AlterUniqueTogether(
            name='groupkeydateexception',
            unique_together={('key_date', 'group')},
        ),
    ]
